---
title: "Week 6 Presentation"
author: "Emma Li"
format: html
editor: visual
---

## Cosmos

### Overview

-   Stands for California State Summer School for Mathematics & Science
-   For rising 9s to rising 12s
-   4 week program living on a UC campus
    -   Second week of July to first week of August
-   5 campuses: UC Davis, UC Irvine, UC Los Angeles, UC San Diego, UC Santa Cruz
-   Each campus offers different topics, called clusters
    -   All STEM related
-   You apply to 1 campus with a first choice cluster and a second choice cluster

### Application

-   Opens second week of January, closes second week of February
-   Application consists of:
    -   Information about contacts, school information, transcripts, activities information and 3 small essays
    -   1 essay for why you chose your first choice cluster (200 words limit), 1 for why you chose your second choice cluster (200 words limit), 1 about you (300 word limit)
    -   Preferably have 2 recommendation letters

### Cosmos Life

-   Dorm with 1 to 2 other people
-   Meals are provided at the cafeteria
-   Classes are from 9 to 3:30ish with an hour break for lunch Monday to Friday
-   Evening activities from 7:30 to 9:30 Monday to Friday
-   Saturday is a field trip day
-   Sunday has no activities
-   Off campus trips to nearby town center roughly twice per week
-   You can get picked up by parent over the weekends
-   Work on a capstone project / poster which will be presented the last Friday

## Questions for Career Development Workshop

1.  What is the most interesting research project you have worked on?
2.  What topics are you interested in researching / why are you interested in these topics?
3.  Which grade levels do you teach / what classes do you teach?
4.  What do you enjoy about teaching?
5.  When did you become interested in data science and statistics?
6.  What where you interests you about data science and statistics?
7.  Throughout your education, did you encounter many other girls and women in the same field of work as you?
8.  Can you give an example of experiences where mentorship really helped you?
9.  What difficulties did you face and how did you work through it?
10. How do you think AI will affect the fields you're working in?
